clientes/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.LandView.as_view(),name="home"),
    path('nuevo', views.AddView.as_view(),name="add"),
    path('consulta/<str:email>', views.DView.as_view(),name="detail"),
    path('actualizar/<int:pk>', views.Update_View.as_view(),name="update"),
    path('eliminar/<int:pk>', views.Delete_View.as_view(),name="delete"),
    path('api/<str:email>', views.consult,name="api_consult"),
    path('consulta_api/<str:email>', views.consult_view,name="detalle"),
] 

prueba_tecnica/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('',include('clientes.urls')),
    path('admin/', admin.site.urls),
]
 

clientes/models.py
from msilib.schema import Class
from django.db import models

# Create your models here.

class Cliente(models.Model):
    nombre = models.CharField(null=False,max_length=255)
    apellido = models.CharField(null=True,max_length=255)
    nacimiento = models.DateField(null=True)
    telefono = models.CharField(null=True,max_length=255)
    email = models.EmailField(null=False,max_length=255)

    class Meta:
        db_table = 'Cliente'

    def __str__(self):
        return self.nombre
 

clientes/views.py
import json
import requests
from django.http import HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, CreateView, DetailView, UpdateView, DeleteView
from django.http import Http404

from .models import Cliente

class LandView(ListView):
    template_name = "land_page.html"
    model = Cliente
    context_object_name = 'clientes'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        clientes = self.get_queryset()
        clientes = Cliente.objects.all()
        context['clientes'] = clientes

        return context

class AddView(CreateView):
    template_name = "formulario.html"
    model = Cliente
    fields = ('nombre','apellido','nacimiento','email','telefono',)
    success_url = reverse_lazy('home')

class DView(DetailView):
    template_name = "consulta.html"
    model = Cliente
    context_object_name = 'cliente'
    slug_field = 'email'
    slug_url_kwarg = 'email'
    
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        clientes = self.get_queryset()
        clientes = Cliente.objects.filter(email=kwargs['object'].email)
        context['clientes'] = clientes
        return context

class Update_View(UpdateView):

    model = Cliente
    template_name = 'actualizacion.html'
    context_object_name = 'client'
    fields = ('nombre','apellido','nacimiento','email','telefono',)

    def get_success_url(self):
        return reverse_lazy('home')

class Delete_View(DeleteView):
    model = Cliente
    template_name = 'eliminar.html'
    success_url = reverse_lazy('home')

def consult_view(request, email):    
    context = []
    url ="http://localhost:8000/api/" + email
    resp = requests.get(url)
    context = resp.json()

    return render(request, 'consult.html', context)

def consult(request,email):
    try:
        clientes = Cliente.objects.filter(email=email)
        context = {
            'id': clientes[0].id,
            'nombre' : clientes[0].nombre,
            'apellido' : clientes[0].apellido,
            'fecha_de_nacimiento' : str(clientes[0].nacimiento),    
            'email' : clientes[0].email,
            'telefono' : clientes[0].telefono,
        }
    except : 
        context = {
            'error': "Cliente no encontrado"
        }
    
    json_object = json.dumps(context,indent=4) 
    return HttpResponse(json_object)

clientes/templates/actualizacion.html
{% extends "land_page.html" %}

{% block content %}
    <div class="card">
        <div class="card-header">
            <h5 class="card-title">Cliente #{{book.id}} Actualizando</h5>
        </div>
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                <div class="row mt-4">
                    <div class="col-2">
                        <label for="id_nombre">Nombre:</label>
                    </div>
                    <div class="col-6">
                        {{form.nombre}}
                    </div>
                </div>
                {% csrf_token %}
                <div class="row mt-4">
                    <div class="col-2">
                        <label for="id_apellido">Apellido:</label>
                    </div>
                    <div class="col-6">
                        {{form.apellido}}
                    </div>
                </div>
                {% csrf_token %}
                <div class="row mt-4">
                    <div class="col-2">
                        <label for="id_email">Email:</label>
                    </div>
                    <div class="col-6">
                        {{form.email}}
                    </div>
                </div>
                {% csrf_token %}
                <div class="row mt-4">
                    <div class="col-2">
                        <label for="id_telefono">Telefono:</label>
                    </div>
                    <div class="col-6">
                        {{form.telefono}}
                    </div>
                </div>
                {% csrf_token %}
                <div class="row mt-4">
                    <div class="col-2">
                        <label for="id_nacimiento">Fecha de Nacimiento (yyyy-mm-dd):</label>
                    </div>
                    <div class="col-6">
                        {{form.nacimiento}}
                    </div>
                </div>
                <button type="submit" class="btn btn-success mt-4">Actualizar</button>
            </form>
        </div>
    </div>
{% endblock content %} 

clientes/templates/consult.html
{% extends "land_page.html" %}

{% block content %}
<div class="card">
    <div class="card-header">
        <h5 class="card-title">Detalle de Cliente</h5>
    </div>
    {% if error %}
        <div class="card-body">
            <div class="row">
                {{ error }}
            </div>
        </div>
    {% else %}
        <div class="card-body">
            <div class="row">
                <div class="row mt-4">
                    <div class="col-2">
                        <label for="id_nombre">Nombre:</label>
                    </div>
                    <div class="col-6">
                        {{nombre}}
                    </div>
                </div>
                <div class="row mt-4">
                    <div class="col-2">
                        <label for="id_apellido">Apellido:</label>
                    </div>
                    <div class="col-6">
                        {{apellido}}
                    </div>
                </div>
                <div class="row mt-4">
                    <div class="col-2">
                        <label for="id_email">Email:</label>
                    </div>
                    <div class="col-6">
                        {{email}}
                    </div>
                </div>
                <div class="row mt-4">
                    <div class="col-2">
                        <label for="id_telefono">Telefono:</label>
                    </div>
                    <div class="col-6">
                        {{telefono}}
                    </div>
                </div>
                <div class="row mt-4">
                    <div class="col-2">
                        <label for="id_nacimiento">Fecha de Nacimiento:</label>
                    </div>
                    <div class="col-6" id="fnacimiento">
                        {{fecha_de_nacimiento}}
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
</div>
{% if id %}
    <a class="btn btn-success" href="{% url 'update' pk=id %}" role="button">Actualizar</a>
    <a class="btn btn-danger" href="{% url 'delete' pk=id %}" role="button">Eliminar</a>
{% endif %}
{% endblock content %} 

clientes/templates/consulta.html
{% extends "land_page.html" %}

{% block content %}
<div class="card">
    <div class="card-header">
        <h5 class="card-title">Detalle de Cliente</h5>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="row mt-4">
                <div class="col-2">
                    <label for="id_nombre">Nombre:</label>
                </div>
                <div class="col-6">
                    {{cliente.nombre}}
                </div>
            </div>
            <div class="row mt-4">
                <div class="col-2">
                    <label for="id_apellido">Apellido:</label>
                </div>
                <div class="col-6">
                    {{cliente.apellido}}
                </div>
            </div>
            <div class="row mt-4">
                <div class="col-2">
                    <label for="id_email">Email:</label>
                </div>
                <div class="col-6">
                    {{cliente.email}}
                </div>
            </div>
            <div class="row mt-4">
                <div class="col-2">
                    <label for="id_telefono">Telefono:</label>
                </div>
                <div class="col-6">
                    {{cliente.telefono}}
                </div>
            </div>
            <div class="row mt-4">
                <div class="col-2">
                    <label for="id_nacimiento">Fecha de Nacimiento:</label>
                </div>
                <div class="col-6">
                    {{cliente.nacimiento}}
                </div>
            </div>
        </div>
    </div>
</div>
<a class="btn btn-success" href="{% url 'update' pk=cliente.id %}" role="button">Actualizar</a>
<a class="btn btn-danger" href="{% url 'delete' pk=cliente.id %}" role="button">Eliminar</a>

{% endblock content %} 

clientes/templates/eliminar.html
{% extends "land_page.html" %}

{% block content %}
    <div class="card">
        <div class="card-header">
            <h5 class="card-title">Eliminar Cliente #{{object.id}}</h5>
        </div>
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                <div class="alert alert-warning" role="alert">
                    Estas seguro de eliminar el cliente <strong>{{ object }}</strong> ?
                </div>
                <button type="submit" class="btn btn-danger">Eliminar</button>
            </form>
        </div>
    </div>
{% endblock content %} 

clientes/templates/formulario.html
{% extends 'land_page.html' %}

{% block content %}
    <div class="card">
        <div class="card-header">
            <h5 class="card-title">Nuevo Cliente</h5>
        </div>
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                <div class="row mt-4">
                    <div class="col-2">
                        <label for="id_nombre">Nombre:</label>
                    </div>
                    <div class="col-6">
                        {{form.nombre}}
                    </div>
                </div>
                {% csrf_token %}
                <div class="row mt-4">
                    <div class="col-2">
                        <label for="id_apellido">Apellido:</label>
                    </div>
                    <div class="col-6">
                        {{form.apellido}}
                    </div>
                </div>
                {% csrf_token %}
                <div class="row mt-4">
                    <div class="col-2">
                        <label for="id_email">Email:</label>
                    </div>
                    <div class="col-6">
                        {{form.email}}
                    </div>
                </div>
                {% csrf_token %}
                <div class="row mt-4">
                    <div class="col-2">
                        <label for="id_telefono">Telefono:</label>
                    </div>
                    <div class="col-6">
                        {{form.telefono}}
                    </div>
                </div>
                {% csrf_token %}
                <div class="row mt-4">
                    <div class="col-2">
                        <label for="id_nacimiento">Fecha de Nacimiento (yyyy-mm-dd):</label>
                    </div>
                    <div class="col-6">
                        {{form.nacimiento}}
                    </div>
                </div>
                <button type="submit" class="btn btn-success mt-4">Crear</button>
            </form>
        </div>
    </div>
{% endblock content %} 

clientes/templates/land_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home' %}"><i class="fa-solid fa-house"></i></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'add' %}">Agregar Cliente</a>
                    </li>
                </ul>
                <form class="d-flex">
                <input class="form-control me-2" id="search" type="search" placeholder="Buscar por Email" aria-label="Search">
                <a class="btn btn-outline-success" onclick="search_function()">Buscar</a>
                </form>
                <script>
                    function search_function(){
                        var email2 = document.getElementById('search').value;
                        var url = "/consulta_api/"+email2;
                        location.href=url;
                    }
                </script>
            </div>
        </div>
    </nav>
    {% block content %}

        <div class="container mt-5" id="container">
            <table class="table table-dark">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Nombre</th>
                        <th scope="col">Apellido</th>
                        <th scope="col">Fecha de Nacimiento</th>
                        <th scope="col">Email</th>
                        <th scope="col">Telefono</th>
                        <th class="disp" scope="col">Actualizar</th>
                        <th class="disp" scope="col">Eliminar</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cliente in clientes %}
                    <tr>
                        <th scope="row"><a href="{% url 'detalle' email=cliente.email %}" class="text-danger text-decoration-none">{{ cliente.id }}</a></th>
                        <td>{{ cliente.nombre }}</td>
                        <td>{{ cliente.apellido }}</td>
                        <td>{{ cliente.nacimiento }}</td>
                        <td>{{ cliente.email }}</td>
                        <td>{{ cliente.telefono }}</td>
                        <td class="disp"><a class="btn btn-success" href="{% url 'update' pk=cliente.id %}" role="button">Actualizar</a></td>
                        <td class="disp"><a class="btn btn-danger" href="{% url 'delete' pk=cliente.id %}" role="button">Eliminar</a></td>
                    </tr>
                    {% endfor %}
                </tbody>

            </table>
            <button type="button" class="btn btn-secondary" id="btnExport" onclick="exportReportToExcel(this)">Descargar Excel</button>
        </div>

    <script>
        function exportReportToExcel() {
            let table = document.getElementsByTagName("table");
            TableToExcel.convert(table[0], {
                name: `clientes.xlsx`, 
                sheet: {
                name: 'tabla clientes'  
                }
            });
        }

    </script>
    {% endblock content %}
    
    <script src="https://cdn.jsdelivr.net/gh/linways/table-to-excel@v1.0.4/dist/tableToExcel.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>